### ISSUE TITLE
AttributeError: module 'types' has no attribute 'Union' python3.10

### ISSUE THREAD

**Issue by Dimfred** [PrettyWood/typingx#4]
Hi, 
when importing the module I get an error. It is new and most certainly related to python3.10:

    Python 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0] on linux                     
    Type "help", "copyright", "credits" or "license" for more information.                             
    @>>> import typingx                                                                    
    Traceback (most recent call last):                                                                 
      File "<stdin>", line 1, in <module>                                                              
      File "/home/dimfred/.local/lib/python3.10/site-packages/typingx/__init__.py", line 4, in <module>
        from .main import isinstancex, issubclassx                                                  
      File "/home/dimfred/.local/lib/python3.10/site-packages/typingx/main.py", line 29, in <module>
        UNION_TYPES = {Union, types.Union}                           
    AttributeError: module 'types' has no attribute 'Union'

**Comment by PrettyWood** [comment]
Thanks for reporting @Dimfred 
I released v0.6 that supports the official python 3.10 release

**Comment by Dimfred** [comment]
@PrettyWood thanks a lot everything works now :)
